### ISSUE TITLE
Not able to Update an User role

### ISSUE THREAD

**Issue by JvDrunen** [Devolutions/devolutions-server#110]
Hi,

I am trying to update the userroles with some security settings through the powershell module.
THe moment i try this i got an error message (in powershell module 2022.2.6.1)
when adding the -debug switch (and looking through the code) i notice that the function Get-DSRoles is used (which does not exisits in the module)

`DEBUG: [Exception] System.Management.Automation.CommandNotFoundException: The term 'Get-DSRoles' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
InvalidOperation: C:\Users\name\Documents\PowerShell\Modules\Devolutions.Server\2022.2.6.1\Public\Roles\Update-DSRole.ps1:118
Line |
 118 |          If ($res.isSuccess) {
     |              ~~~~
     | The variable '$res' cannot be retrieved because it has not been set.`

![image](https://user-images.githubusercontent.com/30151600/198556089-aa985b49-a9d2-4d27-97c4-2f5e9552b021.png)

**Comment by AlexMartigny** [comment]
Hello JvDrunen,

Thank you for bringing this to my attention. I have submitted a fix for this issue, but I am not able to publish a version prior to 2022.3.x to PSGallery, so you will have to download the module from GitHub and import that version in your script.

Please make sure you download the latest 2022.2.X release.

Best regards,
Alexandre
