### ISSUE TITLE
Suggestions for function design in PowerShell module

### ISSUE THREAD

**Issue by peetrike** [Devolutions/devolutions-server#23]
I would like to see PowerShell module here following more guidelines provided by https://docs.microsoft.com/powershell/scripting/developer/cmdlet/windows-powershell-cmdlet-concepts

The referred document is old (and considered legacy) but recommendations are still valid.  And many of these guidelines could be also followed when writing functions instead of compiled cmdlets.

For example, You have functions Get-DSEntry and Get-DSEntries.  When comparing to cmdlet Get-Process, your 2 functions could be one function with 2 parameter sets: with -EntryId it would return only one result, without it there could be some filtering parameters to be able to return 0 or more entries.  And same principle could be applied to all functions with verb 'Get'

**Comment by mauricecote** [comment]
Hello,

Thank you for your input, we will study that and see how we can improve this. Finding best practices is really a case of "google is my enemy" as we find wildly diverging opinions.

I work with most PAM leaders (well, I use their APIs to design integrations with Remote Desktop Manager...) and the current module architecture is based on the patterns that seemed easier to use in those third party modules.

That being said, this is a work in progress and we value the community's input, keep 'em coming!

**Comment by peetrike** [comment]
APIs are usually designed as developers see them fit their needs.

PowerShell module functions/cmdlets are used from commandline and that adds one layer of usage scenarios.  Not all module developers care about that, but well-designed list of commands makes command-line administration usage much easier...
