### ISSUE TITLE
Filtering on Get-DSEntries

### ISSUE THREAD

**Issue by keiransteele-phocas** [Devolutions/devolutions-server#38]
It would be good to add a filter to Get-DSEntries. I can see that it isn't available in the v2021.6.0 branch. I could probably add it myself but there is no public REST API documentation (If there was I wouldn't be using the powershell module).

We want to run a Powershell AWS Lambda to export secrets from Devolutions and insert them into AWS Parameter store so they're usable in Terraform and Ansible.

**Comment by mauricecote** [comment]
its on the roadmap, but depends on the endpoint to be improved.  Since our next major release will be DVLS 2021.2 in October, this has to wait.
