### ISSUE TITLE
Throw a more descriptive error message when the session has timed out

### ISSUE THREAD

**Issue by keiransteele-phocas** [Devolutions/devolutions-server#39]
When running commands I've received random exceptions with no real relevance to the error message. I've started troubleshooting a number of times only to realise that my session has expired.

This is an example of output that I received because the session expired.

```Powershell
New-DSCredentialEntry -connectionsubtype Default -entryname test3 -username test3 -password e0wtw49t8hsg08 -verbose
VERBOSE: [New-DSCredentialEntry] Beginning...
VERBOSE: [Set-DSVaultsContext] begin...
VERBOSE: [Set-DSVaultsContext] about to call with /api/security/vaults/change
VERBOSE: [Invoke-DS] begin...
VERBOSE: [Set-DSVaultsContext] Exception occurred ...
InvalidOperation: /home/user/.local/share/powershell/Modules/Devolutions.Server/Public/Entries/New-DSCredentialEntry.ps1:135
Line |
 135 |          if ($res.isSuccess) {
     |              ~~~~
     | The variable '$res' cannot be retrieved because it has not been set.
```

When you enable the debug flag, there is the message ```DEBUG: [Exception] System.Management.Automation.RuntimeException: Not initialized, please use New-DSSession``` when running directly against "Set-DSVaultsContext", I think this should really be caught and presented to the user even if verbose or debug is not enabled.

Even the above exception message isn't consistently presented. If you run "New-DSCredentialEntry" with -debug you get this instead 
```
DEBUG: [Exception] Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord) in /PowerShell/src/System.Management.Automation/engine
```

**Comment by mauricecote** [comment]
Indeed, we have created a wrapper for the _is-logged_ endpoint that will be put to use, and we have already changed the code to better react to a loss of connectivity.  It should be in our next release.

**Comment by keiransteele-phocas** [comment]
Will this allow the API to work with MFA enabled or is there some other method other than username and password? I enabled MFA on my account but the module seems to have no awareness that it's enabled, tries to log in anyway and subsequent requests just 401. Before enabling MFA it worked fine.

```Powershell
VERBOSE: POST https://drds.domain.com/dvls/api/login/partial with 559-byte payload
VERBOSE: received 986-byte response of content type application/json
VERBOSE: [New-DSSession] Successfully logged in to Devolutions Server
VERBOSE: ServerResponse
VERBOSE: Retrieving all entries from Devolutions...
VERBOSE: [Get-DSEntries] begin...                                                                                                                                                                                                                        
VERBOSE: [Get-DSEntriesLegacy] begin...
VERBOSE: [Set-DSVaultsContext] begin...
VERBOSE: [Set-DSVaultsContext] about to call with https://drds.domain.com/dvls/api/security/vaults/change
VERBOSE: [Invoke-DS] begin...
VERBOSE: PUT https://drds.domain.com/dvls/api/security/vaults/change with 38-byte payload
VERBOSE: received 61-byte response of content type application/json
DEBUG: [Exception] Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 401 (Unauthorized). at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord) in /PowerShell/src/System.Management.Automation/engine/MshCommandRuntime.cs:line 2080
```

**Comment by mauricecote** [comment]
Hello,  the first step was not to handle MFA challenges, because we do have an account type named "Application" that I suspect would be the favored way of using the REST API.

Not to say that we wont support interactive sessions, but with the limited engineering time we have we need to make choices.
