### ISSUE TITLE
Unencrypted Data returned by Get-DSEntry

### ISSUE THREAD

**Issue by keiransteele-phocas** [Devolutions/devolutions-server#40]
If the purpose of Get-DSEntrySensitiveData is to retrieve the unencrypted password or private key (I'm assuming that's it's purpose, that's how it works but it's not documented), why is an unencrypted private key being returned when using Get-DSEntry as well?

**Comment by mauricecote** [comment]
since this is a security issue we will transfer it to our internal ticketing system.  This issue will be deleted shortly.
