### ISSUE TITLE
Login/Auth Flow Requirements

### ISSUE THREAD

**Issue by keiransteele-phocas** [Devolutions/devolutions-server#49]
I'm attempting to reverse engineer the parts of your module in Golang that I need to run in a Lambda as the Powershell simply doesn't work.

Are you able to provide any information on the requirements when providing the SafePassword and SafeSessionKey? What format, ciphers, encryption etc that the API expects? I have written a module that will output what I believe I need from looking at the Powershell but when I post them to the login endpoint, I just get an Invalid Username/Password message. When I post a SafePassword and SafeSessionKey from the Powershell I stripped out of your module, I am able to successfully log in.

Thanks.

**Comment by mauricecote** [comment]
I cannot give other information that you cannot already see in the code, it creates everything as needed.  If the problem is that its hard to convert from powershell, maybe consulting the Python SDK will help.  You will find it at https://github.com/Devolutions/dps-sdk-python
