### ISSUE TITLE
typo in NonSupportedEntry.ps

### ISSUE THREAD

**Issue by HoppeAndreas** [Devolutions/devolutions-server#92]
when testing the script i get an error 

InvalidOperation: The variable '$Response' cannot be retrieved because it has not been set with line 43.
Should this be the $res from line 41 ?

**Comment by AlexMartigny** [comment]
Hello,

Although you're right, this script only serves as an example and is not meant to be executed as is. I recommend you write your own script based on this sample.

Thanks for letting me know, I'll change this line.

Have a good day Andreas!
